# hw0
comp0-1:
	g++ --std=c++17 -o hw0_1 main_hw0_1.cpp

run0-1: comp0-1
	./hw0_1

comp0-2:
	g++ --std=c++17 -o hw0_2 main_hw0_2.cpp

run0-2: comp0-2
	./hw0_2

# hw1
comp1-1:
	g++ --std=c++17 -o hw1_1 main_hw1_1.cpp

run1-1: comp1-1
	./hw1_1

comp1-2:
	g++ --std=c++17 -o hw1_2 main_hw1_2.cpp

run1-2: comp1-2
	./hw1_2
