comp1:
	g++ --std=c++17 -o hw3_1 main_hw3_1.cpp

run1: comp1
	./hw3_1

comp2:
	g++ --std=c++17 -o hw3_2 main_hw3_2.cpp

run2: comp2
	./hw3_2

comp3:
	g++ --std=c++17 -o hw3_3 main_hw3_3.cpp

run3: comp3
	./hw3_3
